name: Validate PR
on:
  push:
    branches:
      - '*'
env:
  HUSKY: 0
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package-validation:
    name: Package validation
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Enable yarn
        run: corepack enable

      - name: Package audit
        run: yarn npm audit

  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - run: |
          corepack enable

      - name: Restore dependencies
        id: restore-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        if: ${{ steps.restore-dependencies.outputs.cache-hit != 'true' }}
        run: yarn

      - name: Validate types
        run: yarn types

      - name: Validate linters
        run: yarn lint
